version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: carbon_credit_mqtt
    ports:
      - "1883:1883"    # MQTT port
      - "9001:9001"    # WebSocket port
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    restart: unless-stopped
    networks:
      - mqtt_network

  mqtt-explorer:
    image: smeagolworms4/mqtt-explorer
    container_name: mqtt_explorer
    ports:
      - "4000:4000"
    environment:
      - MQTT_EXPLORER_SERVER_HOST=mosquitto
      - MQTT_EXPLORER_SERVER_PORT=1883
    depends_on:
      - mosquitto
    restart: unless-stopped
    networks:
      - mqtt_network

networks:
  mqtt_network:
    driver: bridge
